language: python
python:
    - "3.4"
install:
    - "python setup.py install"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "coverage run --source=zeroless setup.py test"
after_success:
    coveralls
